# Assignment: 100 numpy exercises

### 1. Import the numpy package under the name np

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.

In [2]:
print("NumPy v"+ np.__version__)
np.show_config()

NumPy v1.26.0
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1695830428084/_build_env/bin/x86_64-conda-linux-gnu-cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.0",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "11.2.0",
      "commands": "/croot/numpy_and_numpy_base_1695830428084/_build_env/bin/x86_64-conda-linux-gnu-c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "mkl-sdl",
      "found": true,
      "version": "2023.1",
      "detection method": "pkgconfig",
      "include direc

/home/ultimate/miniconda3/envs/datascience/lib/python3.9/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Create a null vector of size 10

In [3]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array

In [4]:
array = np.zeros((3, 5))
print(array.size * array.itemsize, 'bytes')

120 bytes


### 5. How to get the documentation of the numpy add function from the command line?


> python -c "import numpy; numpy.info(numpy.add)"

In [5]:
!python -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

### 6. Create a null vector of size 10 but the fifth value which is 1

In [6]:
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [7]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8. Reverse a vector (first element becomes last)

In [8]:
reversed_vector = np.flip(vector)
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### 9. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 10. Find indices of non-zero elements from [4, 5, 0, 7, 0, 0]

In [10]:
non_zero_indices = np.nonzero([4, 5, 0, 7, 0, 0])
print(non_zero_indices)

(array([0, 1, 3]),)


### 11. Create a 3x3 identity matrix

In [11]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 12. Create a 3x3x3 array with random values

In [12]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.73320447 0.13817256 0.64828624]
  [0.08469638 0.43177769 0.16981166]
  [0.95053753 0.37485172 0.54736581]]

 [[0.26554697 0.86094398 0.08521733]
  [0.32499672 0.84484081 0.26809185]
  [0.36733796 0.42142995 0.50428115]]

 [[0.27226119 0.93975086 0.06639082]
  [0.15030207 0.85367841 0.17985694]
  [0.86303371 0.75533938 0.85331743]]]


### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
random_v = np.random.random((10, 10))
min_value = random_v.min()
max_value = random_v.max()
print(f"10x10 array random values: \n{random_v}")
print(f"\nmin: {min_value}\nmax: {max_value}")

10x10 array random values: 
[[0.53315794 0.16766268 0.04044148 0.39320562 0.80268701 0.47274948
  0.2431193  0.46002088 0.35522469 0.00994336]
 [0.77844099 0.86429403 0.65402609 0.69795463 0.31696794 0.95474132
  0.54694202 0.47542654 0.35687999 0.9146977 ]
 [0.77991924 0.83374557 0.38702292 0.58827917 0.39040211 0.39263116
  0.45555446 0.36970781 0.0134607  0.39774263]
 [0.42048226 0.87749896 0.1922951  0.39804862 0.91586972 0.78126756
  0.20645745 0.93874423 0.18261094 0.63702093]
 [0.67236705 0.8085486  0.09542605 0.80710574 0.31198901 0.98868672
  0.96243801 0.31603136 0.3023215  0.10871761]
 [0.73106269 0.98676796 0.86371833 0.63202892 0.56524462 0.25362392
  0.66250108 0.51893105 0.91837001 0.75994908]
 [0.97897956 0.70903881 0.17278331 0.90470944 0.6499621  0.95697564
  0.75230374 0.16282359 0.35070019 0.35736062]
 [0.35271209 0.10088538 0.09665579 0.90913934 0.2833812  0.29659764
  0.0702372  0.3347     0.86526209 0.15403347]
 [0.11611399 0.16031351 0.70932183 0.81799443 0.7305

### 14. Create a random vector of size 30 and find the mean value

In [14]:
random_vector = np.random.random(30)
mean_value = random_vector.mean()
print(mean_value)

0.4667937303085639


### 15. Create a 2d array with 1 on the border and 0 inside

In [15]:
border_array = np.ones((4, 4))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


### 16. How to add a border (filled with 0's) around an existing array?

In [16]:
existing_array = np.ones((3, 3))
new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)
print(new_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


### 17. What is the result of the following expression?

In [17]:
print(0 * np.nan)  
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan])) 
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
diagonal_matrix = np.diag(1 + np.arange(4), k=-1)
print(diagonal_matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. Create an 8x8 matrix and fill it with a checkerboard pattern

In [19]:
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print(checkerboard_matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
print(np.unravel_index(99, (6, 7, 8)))

(1, 5, 3)


### 21. Create a checkerboard 8x8 matrix using the tile function

In [21]:
checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 22. Normalize a 5x5 random matrix

In [22]:
A = np.random.random((5, 5))
normalized_A = (A - A.min()) / (A.max() - A.min())
print(normalized_A)

[[0.96115388 1.         0.62919444 0.19312562 0.91500479]
 [0.83642342 0.93458609 0.28306248 0.73802422 0.53981694]
 [0.20249796 0.06603761 0.60234712 0.27931883 0.25843589]
 [0.90645872 0.00196647 0.41029541 0.01446395 0.        ]
 [0.76026736 0.12704306 0.34646064 0.44332105 0.98253234]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [23]:
color = np.dtype([('R', np.ubyte),
                    ('G', np.ubyte),
                    ('B', np.ubyte),
                    ('A', np.ubyte)])

### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [24]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
print(np.dot(A, B))

[[0.44775063 0.3393014 ]
 [1.1652377  1.05918961]
 [1.19707472 1.04365734]
 [0.71694415 0.55317085]
 [1.06222289 0.77537768]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [25]:
A = np.arange(10)
A[(A > 3) & (A < 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


### 26. What is the output of the following script?

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### 27. Consider an integer vector Z, which of these expressions are legal?

In [27]:
Z = np.arange(5)
print(Z**Z)         # Legal (element-wise power)
print(2 << Z >> 2)  # Legal (bitwise shift)
print(Z <- Z)       # Legal (element-wise comparison)
print(1j*Z)         # Legal (complex multiplication)
print(Z/1/1)        # Legal (element-wise division)
#print(Z<Z>Z)        # Illegal (chained comparison)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28. What are the result of the following expressions?

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

### 29. How to round away from zero a float array?

In [ ]:
A = np.random.uniform(-10, 10, 10)
print(np.copysign(np.ceil(np.abs(A)), A))

### 30. How to find common values between two arrays?

In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])
common_values = np.intersect1d(A, B)
print(common_values)

### 31. How to ignore all numpy warnings (not recommended)?

In [ ]:
np.seterr(all='ignore')
np.arange(4) / 0

### 32. Is the following expression true?

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

### 33. How to get the dates of yesterday, today and tomorrow?

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(f"Yesterday: {yesterday}")
print(f"Today: {today}")
print(f"Tomorrow: {tomorrow}")

### 34. How to get all the dates corresponding to the month of July 2016?

In [ ]:
dates_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_july_2016)

### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [ ]:
A = np.ones(3)
B = np.ones(3) * 2
print(A)
print(B)
print(np.multiply(A + B, -A / 2, out=(A + B)))


### 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [ ]:
A = np.random.uniform(0, 10, 5)
print(A.astype(int))
print(np.floor(A))
print(np.ceil(A) - 1)
print(np.trunc(A))

### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [ ]:
A = np.tile(np.arange(5), (5, 1))
print(A)

### 38. Consider a generator function that generates 10 integers and use it to build an array

In [ ]:
def generator():
    for i in range(10):
        yield i

print(np.fromiter(generator(), dtype=int))

### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [ ]:
A = np.linspace(0, 1, 12)[1:-1]
print(A)

### 40. Create a random vector of size 10 and sort it

In [ ]:
A = np.random.random(10)
A.sort()
print(A)

### 41. How to sum a small array faster than np.sum?

In [ ]:
A = np.arange(10)
print(np.add.reduce(A))

### 42. Consider two random array A and B, check if they are equal

In [ ]:
A = np.random.random(5)
B = np.random.random(5)
print(np.array_equal(A, B))

### 43. Make an array immutable (read-only)

In [ ]:
A = np.zeros(10)
A.flags.writeable = False
A[0] = 4

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [ ]:
A = np.random.random((10, 2))
x, y = A[:, 0], A[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print(np.column_stack((r, theta)))

### 45. Create random vector of size 10 and replace the maximum value by 0

In [ ]:
A = np.random.random(10)
A[A.argmax()] = 0
print(A)

### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [ ]:
A = np.zeros((5, 5), [('x', float), ('y', float)])
A['x'], A['y'] = np.meshgrid(np.linspace(0, 1, 5),
                                                            np.linspace(0, 1, 5))
print(A)

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij = 1/(xi - yj))

In [ ]:
X = np.arange(10)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

### 48. Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
for dtype in np.sctypes['int'] + np.sctypes['uint'] + [np.float16, np.float32, np.float64]:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
        print(f"{dtype}: {info.min} to {info.max}")
    elif np.issubdtype(dtype, np.floating):
        info = np.finfo(dtype)
        print(f"{dtype}: {info.min} to {info.max}")

### 49. How to print all the values of an array?

In [ ]:
np.set_printoptions(threshold=np.inf)
A = np.arange(200)
print(A)

### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
A = np.arange(10)
scalar = 7.5
closest_value = A[(np.abs(A - scalar)).argmin()]
print(closest_value)

### 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [ ]:
A = np.zeros(1, [('position', [('x', float), ('y', float)]),
                                               ('color', [('r', int), ('g', int), ('b', int)])])
print(A)

### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [ ]:
A = np.random.random((10,2))
X,Y = np.atleast_2d(A[:,0], A[:,1])
Distance = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(Distance)


### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
float_32 = np.arange(10, dtype=np.float32)
int_32 = float_32.view(np.int32)
print(int_32)

### 54. How to read the following file?

In [ ]:
from io import StringIO

A = StringIO('''1, 2, 3, 4, 5
     6,  ,  , 7, 8
     ,  , 9,10,11
''')

data = np.genfromtxt(A, delimiter=",", dtype=np.int_)
print(data)

### 55. What is the equivalent of enumerate for numpy arrays?

In [ ]:
A = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(A):
    print(index, value)

### 56. Generate a generic 2D Gaussian-like array

In [ ]:
import numpy as np
x, y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
gaussian_array = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ))
print(gaussian_array)

### 57. How to randomly place p elements in a 2D array?

In [ ]:
p = 3
A = np.zeros((5, 5))
np.put(A, np.random.choice(range(5*5), p, replace=False), 1)
print(A)

### 58. Subtract the mean of each row of a matrix

In [ ]:
A = np.random.random((3, 3))
B = A - A.mean(axis=1, keepdims=True)
print(B)

### 59. How to sort an array by the nth column?

In [ ]:
A = np.random.randint(0, 10, (3, 3))
n = 1
sorted_A = A[A[:, n].argsort()]
print(sorted_A)


### 60. How to tell if a given 2D array has null columns?

In [ ]:
A = np.array([[1, 2, 0], [0, 4, 0], [0, 0, 0]])
null_columns = np.all(A == 0, axis=0)
print(null_columns)

### 61. Find the nearest value from a given value in an array

In [ ]:
given_value = 5.5
random_values = np.random.random(10)
nearest_value = random_values[np.abs(random_values - given_value).argmin()]
print(nearest_value)

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [ ]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
sum_iterator = np.nditer([A, B, None])
for a, b, c in sum_iterator:
    c[...] = a + b
print(sum_iterator.operands[2])

### 63. Create an array class that has a name attribute

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name=""):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, 'name', "")

A = NamedArray(np.arange(5), "range_5")
print (A.name)

### 64. Consider a given vector, how to add 1 to each element indexed by a second vector

In [ ]:
A = np.ones(10)
vector_indices = np.array([0, 1, 2, 3, 3, 4, 4, 5, 5, 6])
np.add.at(A, vector_indices, 1)
print(A)

### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [ ]:
X = np.array([1, 2, 3, 4, 5, 6])
I = np.array([1, 3, 9, 3, 4, 1])
F = np.bincount(I, weights=X)
print(F)

### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [ ]:
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.ubyte)
unique_colors = len(np.unique(image.reshape(-1, 3), axis=0))
print(unique_colors)

### 67. Considering a four dimensions array, how to get sum over the last two axis at once?

In [ ]:
A = np.random.randint(0,10,(2, 3, 4, 5))
sum_last_two_axes = A.sum(axis=(-2, -1))
print(sum_last_two_axes)

### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of the same size describing subset indices?

In [ ]:
vector_D = np.random.random(10)
vector_S = np.random.randint(0, 2, 10)
means_subsets = np.bincount(vector_S, weights=vector_D) / np.bincount(vector_S)
print(means_subsets)

### 69. How to get the diagonal of a dot product?


In [ ]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
diagonal_dot_product = np.diag(np.dot(A, B))
print(diagonal_dot_product)

### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


In [ ]:
A = np.array([1, 2, 3, 4, 5])
B = np.zeros(len(A)+ (len(A) - 1) * 3, dtype=int)
B[::4] = A
print(B)

### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)?

In [ ]:
A_3d = np.ones((5, 5, 3))
A_2d = 3*np.ones((5, 5))
X = A_3d * A_2d[:, :, None]
print(X)

#### 72. How to swap two rows of an array?

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A[[0, 1]] = A[[1, 0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

In [ ]:
triplets = np.random.randint(0, 10, (10, 3))
unique_line_segments = np.unique(triplets[:, [0, 1, 1, 2, 2, 0]].reshape(-1, 2), axis=0)
print(unique_line_segments)

In [ ]:
triplets = np.random.randint(0,10,(10,3))
A = np.roll(triplets.repeat(2,axis=1),-1,axis=1)
A = A.reshape(len(A)*3,2)
A = np.sort(F,axis=1)
B = A.view( dtype=[('p0',A.dtype),('p1',A.dtype)] )
B = np.unique(B)
print(B)

### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

### 75. How to compute averages using a sliding window over an array? 

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(100)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

### 77. How to negate a boolean, or to change the sign of a float inplace?

In [ ]:
A = np.random.randint(0,2,100)
np.logical_not(A, out=A)

### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
`

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))\
    
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)

In [ ]:
def extract_subpart(array, shape, center):
    subpart = np.full(shape, fill_value=np.nan)
    indices = np.array(center) - np.array(shape) // 2
    subpart_shape = np.minimum(shape, np.array(array.shape) - indices)
    subpart[
        tuple(slice(max(0, -i), dim) for i, dim in zip(indices, subpart_shape))
    ] = array[
        tuple(slice(max(0, i), min(dim, i + s)) for i, s, dim in zip(indices, subpart_shape, array.shape))
    ]
    return subpart

A = np.random.random((10, 10))
subpart = extract_subpart(A, (3, 3), (5, 5))
print(subpart)


### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R

In [ ]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, (4,))
print(R)


### 82. Compute a matrix rank

In [ ]:
matrix_rank = np.linalg.matrix_rank(np.random.random((3, 3)))
print(matrix_rank)

### 83. How to find the most frequent value in an array?

In [ ]:
A = np.random.randint(0, 10, 20)
frequent_value = np.bincount(A).argmax()
print(A)
print(f"Most Frequent Value in the Array: {frequent_value}")

### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [ ]:
A = np.random.randint(0,5,(10,10))
print(sliding_window_view(A, window_shape=(3, 3)))

### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(A):
    return np.asarray(A + A.T - np.diag(A.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

In [ ]:
p = 3
n = 5
matrices = np.random.random((p, n, n))
vectors = np.random.random((p, n, 1))
sum_matrix_products = np.sum(matrices @ vectors, axis=0)
print(sum_matrix_products)

### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [ ]:
A = np.ones((16, 16))
block_sum = np.sum(np.lib.stride_tricks.sliding_window_view(A, (4, 4)), axis=(-2, -1))
print(block_sum[::4, ::4, ...])


### 88. How to implement the Game of Life using numpy arrays?

In [ ]:
def game_of_life(board, steps):
    for _ in range(steps):
        neighbors = sum(np.roll(np.roll(board, i, axis=0), j, axis=1)
                        for i in (-1, 0, 1) for j in (-1, 0, 1) if (i != 0 or j != 0))
        board = (neighbors == 3) | (board & (neighbors == 2))
    return board

# Example usage:
initial_board = np.random.choice([0, 1], (50, 50))
final_board = game_of_life(initial_board, steps=10)
print(final_board)

### 89. How to get the n largest values of an array

In [ ]:
A = np.arange(100)
n_largest_indices = np.argsort(A)[-n:]
n_largest_values = A[n_largest_indices]
print(n_largest_values)

### 90. Given an arbitrary number of vectors, build the cartesian product


In [ ]:
import itertools

def cartesian(arrays):
    return np.array(list(itertools.product(*arrays)))

result = cartesian(([1, 2, 3], [4, 5], [6, 7]))
print(result)

### 91. How to create a record array from a regular array?

In [ ]:
A = np.array([(1, 'John', 28), (2, 'Alice', 22), (3, 'Bob', 31)],
              dtype=[('id', int), ('name', 'U10'), ('age', int)])

Record_A = np.array(A, dtype=[('id', int), ('name', 'U10'), ('age', int)])
print(Record_A)


### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [ ]:
# Method 1: Using the ** operator
Z = np.random.random(1000000)
result_1 = Z ** 3
print(result_1)

# Method 2: Using np.power function
result_2 = np.power(Z, 3)
print(result_2)

# Method 3: Using np.einsum for element-wise cube
result_3 = np.einsum('i,i,i->i', Z, Z, Z)
print(result_3)


### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

In [ ]:
A = np.random.randint(0,10,(8,3))
B = np.random.randint(0,10,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

In [ ]:
A = np.random.randint(0, 10, (10, 3))

S = A[np.any(A[:, 1:] != A[:, :-1], axis=1)]

print(S)

### 95. Convert a vector of ints into a matrix binary representation

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

### 96. Given a two dimensional array, how to extract unique rows?

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [1, 2, 3],
              [7, 8, 9],
              [4, 5, 6]])

# Extract unique rows
unique_rows = np.unique(A, axis=0)

print(unique_rows)

### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [ ]:
A = np.random.uniform(1,5,10)
B = np.random.uniform(1,2,10)

# Inner Product
I = np.einsum('i,i->', A, B)
print( f"Result of Inner Product: \n{I}")

# Outer Product
O = np.einsum('i,j->ij', A, B)
print( f"Result of Outer Product: \n{O}")

# Sum
S= np.einsum('i->', A) 
print( f"Result of Sum: \n{S}")

# Element-wise Multiplication
M = np.einsum('i,i->i', A, B)
print( f"Result of Multiplication: \n{ M}")

### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

In [ ]:
import matplotlib.pyplot as plt

def equidistant_samples(X, Y, num_samples):
    t = np.linspace(0, 1, len(X))  # Parameterization from 0 to 1
    t_equidistant = np.linspace(0, 1, num_samples)  # Equidistant parameterization

    sampled_X = np.interp(t_equidistant, t, X)
    sampled_Y = np.interp(t_equidistant, t, Y)

    return sampled_X, sampled_Y


X = np.array([0, 1, 3, 6, 9, 12])
Y = np.array([0, 2, 5, 7, 8, 6])

num_samples = 100
sampled_X, sampled_Y = equidistant_samples(X, Y, num_samples)

# Plot the original path and the sampled points
plt.plot(X, Y, 'o-', label='Original Path')
plt.plot(sampled_X, sampled_Y, 'x', label=f'Equidistant Samples ({num_samples} points)')
plt.legend()
plt.xlabel('X')
plt.ylabel('Y')
plt.title('Sampling a Path with Equidistant Points')
plt.show()

### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)